edit in workflow

diff --git a/.github/workflows/mongo-backup.yml b/.github/workflows/mongo-backup.yml
--- a/.github/workflows/mongo-backup.yml
+++ b/.github/workflows/mongo-backup.yml
@@ -1,8 +1,8 @@
 name: mongoDB Backup
 on:
   schedule:
-  #        Min Hour Day Month DayOfWeek
-    - cron: '30 14 * * *'                   # Runs daily at 14:20 UTC
+    #        Min Hour Day Month DayOfWeek
+    - cron: '30 14 * * *' # Runs daily at 14:20 UTC
   workflow_dispatch:
 jobs:
   backup:
@@ -25,7 +25,12 @@ jobs:
         env:
           MONGO_URI: ${{ secrets.MONGO_URI }}
         run: |
-          mongodump --uri="$MONGO_URI" --out="./backup/mongo_backup_$(date +'%Y-%m-%d_%H-%M-%S')"
+          if [ -z "$MONGO_URI" ]; then
+            echo "ERROR: MONGO_URI is not set!"
+            exit 1
+          fi
+          echo "Connecting to MongoDB..."
+          mongodump --uri="${MONGO_URI}" --out="./backup/mongo_backup_$(date +'%Y-%m-%d_%H-%M-%S')"
 
       - name: Upload backup artifact
         uses: actions/upload-artifact@v4
